language: ruby

rvm:
  - "1.9.3"
  - "2.0.0"

env:
  - DB=sqlite
before_script:
  - mysql -e 'create database myapp_test;'
script:
  - RAILS_ENV=test rake db:create
  - RAILS_ENV=test bundle exec rake